# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20170422_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.IntegerField(choices=[(1, 'Home & Kitchen'), (2, 'Health & Household'), (3, 'Electronics'), (4, 'Clothing, Shoes & Jewelry'), (5, 'Grocery & Gourmet Food'), (6, 'Computers & Accessories')], default=1),
        ),
    ]
