# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170420_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_year',
            field=models.IntegerField(null=True),
        ),
    ]
