# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20170420_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
    ]
